name: api_client
description: A new Flutter package project.
version: 0.0.1
homepage: https://github.com/saidelgnaidy/dio_client

environment:
  sdk: '>=2.18.4 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  connectivity_plus: ^3.0.2
  dartz: ^0.10.1
  dio: ^4.0.6
  freezed_annotation: ^2.2.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
